### ISSUE TITLE
Windows 3.9 Builds fail

### ISSUE THREAD

**Issue by jan-janssen** [conda-forge/pyside2-feedstock#99]
Currently the Windows Python 3.9 builds fails, while the rest of the builds work fine: 
```
2022-01-18T14:08:36.4524037Z Traceback (most recent call last):
2022-01-18T14:08:36.4527223Z   File "D:\bld\pyside2_1642512948215\work\sources\pyside2\PySide2\support\generate_pyi.py", line 332, in <module>
2022-01-18T14:08:36.4528673Z     generate_all_pyi(outpath, options=options)
2022-01-18T14:08:36.4533330Z   File "D:\bld\pyside2_1642512948215\work\sources\pyside2\PySide2\support\generate_pyi.py", line 311, in generate_all_pyi
2022-01-18T14:08:36.4537715Z     generate_pyi(import_name, outpath, options)
2022-01-18T14:08:36.4539514Z   File "D:\bld\pyside2_1642512948215\work\sources\pyside2\PySide2\support\generate_pyi.py", line 227, in generate_pyi
2022-01-18T14:08:36.4540755Z     top = __import__(import_name)
2022-01-18T14:08:36.4541781Z ImportError: DLL load failed while importing QtCore: The specified module could not be found.
2022-01-18T14:08:36.4936467Z NMAKE : fatal error U1077: 'D:\bld\pyside2_1642512948215\_build_env\Library\bin\cmake.exe' : return code '0x1'
2022-01-18T14:08:36.4938741Z Stop.
2022-01-18T14:08:36.4971092Z NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\nmake.exe"' : return code '0x2'
2022-01-18T14:08:36.4972849Z Stop.
2022-01-18T14:08:36.4989965Z NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\nmake.exe"' : return code '0x2'
2022-01-18T14:08:36.4991117Z Stop.
```

**Comment by n-elie** [comment]
It seems that the generate_pyi.py script tries to load the freshly generated `work\sources\pyside2\build\PySide2\QtCore.cp39-win_amd64.pyd` but this DLL cannot be loaded because the pyside2 DLL could not be found (it is located at `work\sources\pyside2\build\libpyside\pyside2.cp39-win_amd64.dll`).
If I copy this DLL to `work\sources\pyside2\build\PySide2`, the build can continue

**Comment by looooo** [comment]
I guess this one can be closed
